services:
  code-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ~/repositories:/home/coder
      - ~/.aws/credentials:/home/coder/.aws/credentials
      - ~/.ssh:/home/coder/.ssh
    environment:
      PASSWORD: "your_strong_password"