services:
  code-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ~/repositories:/home/coder/project
      - ~/.aws/credentials:/home/coder/.aws/credentials
    environment:
      PASSWORD: "your_strong_password"